### ISSUE TITLE
Question about firmware-Rom

### ISSUE THREAD

**Issue by mmueller-kaffeeschluerfercom** [RemoteFlyer/Roland-Edirol-UA-25-firmware-rom#1]
Hi! Is this asm file a disassembly of the original firmware in the EEPROM of the UA-25? Or a new firmware of your own?

**Comment by RemoteFlyer** [comment]
This is the disassembled contents of the EEPROM. I was trying to understand how it worked, but other work took over. I thought it might be a useful reference.

**Comment by mmueller-kaffeeschluerfercom** [comment]
Great, thank you! I use it as a DC-coupled DAQ card, see [https://hackaday.io/project/176715-add-dc-coupled-inputs-to-the-edirol-ua-25](url)
Thanks for your work, I'll try the EX-mod soon to see if the advanced mode works with the newest MacOs... For now I use it with ALSA/Linux
